# Generated by Django 3.2.8 on 2021-11-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='miniature',
            field=models.ImageField(default='default.png', upload_to='publicaciones/images/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.TextField(max_length=100),
        ),
    ]
